//! URL resolver trait for type-safe URL generation.
//!
//! This module provides the [`UrlResolver`] trait, the foundation for
//! compile-time type-safe URL resolution. View macros (`#[get]`, `#[post]`,
//! etc.) generate extension traits with blanket implementations that add
//! named accessor methods to any `UrlResolver` implementor.
//!
//! # Architecture
//!
//! ```text
//! #[get("/login/", name = "auth_login")]  →  trait ResolveAuthLogin
//!     ↓ (blanket impl)
//! ResolvedUrls: UrlResolver  →  urls.auth_login()
//! ```
//!
//! # Usage
//!
//! ```rust,ignore
//! use crate::config::urls::url_prelude::*;
//!
//! let urls = ResolvedUrls::from_global();
//! let login_url = urls.auth_login();           // "/api/auth/login/"
//! let detail_url = urls.cluster_retrieve("x"); // "/api/clusters/x/"
//! ```

/// Base trait for type-safe URL resolution.
///
/// Implementors provide URL lookup by route name and parameters.
/// Extension traits generated by view macros (`#[get]`, `#[post]`, etc.)
/// use this as a supertrait to add named accessor methods via blanket impls.
///
/// # Example
///
/// ```rust
/// use reinhardt_urls::routers::resolver::UrlResolver;
///
/// struct MyResolver;
///
/// impl UrlResolver for MyResolver {
///     fn resolve_url(&self, name: &str, params: &[(&str, &str)]) -> String {
///         format!("/{}/", name)
///     }
/// }
///
/// let resolver = MyResolver;
/// assert_eq!(resolver.resolve_url("home", &[]), "/home/");
/// ```
pub trait UrlResolver {
	/// Resolve a URL by route name and parameters.
	///
	/// # Panics
	///
	/// Implementations should panic if the route name is not registered.
	fn resolve_url(&self, name: &str, params: &[(&str, &str)]) -> String;
}
