//! Server Function Router Extension
//!
//! This module provides the `ServerFnRouterExt` extension trait for registering
//! server functions explicitly with `ServerRouter`.
//!
//! ## Usage
//!
//! ```ignore
//! use reinhardt::pages::server_fn::ServerFnRouterExt;
//! use crate::server_fn::{login, logout, get_user};
//!
//! pub fn routes() -> ServerRouter {
//!     ServerRouter::new()
//!         .server_fn(login)
//!         .server_fn(logout)
//!         .server_fn(get_user)
//! }
//! ```

use super::auto_registration::{collect_auto_server_fns, duplicate_server_fn_path_error};
use super::registration::ServerFnRegistration;
use super::set::ServerFnSetRegistration;
use hyper::header::{CONTENT_TYPE, HeaderValue};
use hyper::{Method, StatusCode};
use reinhardt_core::endpoint::EndpointInfo;
use reinhardt_http::{Handler, Request, Response, Result, SharedResponseCookies};
use reinhardt_urls::routers::ServerRouter;
use reinhardt_urls::routers::server_router::RouteOrigin;
use std::marker::PhantomData;

/// Extension trait for registering server functions with `ServerRouter`.
///
/// This trait provides the `server_fn` method which allows explicit registration
/// of server functions. Unlike the previous `register_all_server_functions()`
/// approach, this makes the registration explicit and visible.
///
/// # Example
///
/// ```ignore
/// use reinhardt::pages::server_fn::ServerFnRouterExt;
/// use crate::server_fn::{login, logout};
///
/// let router = ServerRouter::new()
///     .server_fn(login)    // Explicitly register login
///     .server_fn(logout);  // Explicitly register logout
/// ```
///
/// # Benefits
///
/// - **Explicit**: Clearly shows which server functions are registered
/// - **Type-safe**: Compiler ensures only valid server functions are passed
/// - **IDE-friendly**: Auto-completion and go-to-definition work correctly
/// - **Controllable**: Prevents accidental registration of server functions
pub trait ServerFnRouterExt {
	/// Register a server function with this router.
	///
	/// The server function must have been defined with the `#[server_fn]` macro,
	/// which generates the marker struct passed as the `marker` argument.
	///
	/// # Arguments
	///
	/// * `marker` - The marker struct generated by `#[server_fn]` macro
	///
	/// # Returns
	///
	/// Returns `self` with the server function registered, allowing method chaining.
	///
	/// # Example
	///
	/// ```ignore
	/// use reinhardt::pages::server_fn::ServerFnRouterExt;
	/// use crate::server_fn::login;
	///
	/// let router = ServerRouter::new()
	///     .server_fn(login);
	/// ```
	fn server_fn<S: ServerFnRegistration + 'static>(self, marker: S) -> Self;

	/// Registers every inventory-linked server function owned by the caller's application.
	///
	/// Pass `module_path!()` from the application's router construction module so
	/// ownership is resolved before routes are mounted.
	///
	/// # Example
	///
	/// ```ignore
	/// let router = ServerRouter::new().auto_server_fns(module_path!());
	/// ```
	fn auto_server_fns(self, caller_module: &'static str) -> Self;

	/// Registers inventory-linked server functions owned by one crate instance.
	fn auto_server_fns_in_crate(
		self,
		caller_module: &'static str,
		caller_crate: &'static str,
	) -> Self;

	/// Register every member of a named server function set.
	fn server_fnset<S: ServerFnSetRegistration>(self, set: S) -> Self;
}

impl ServerFnRouterExt for ServerRouter {
	fn server_fn<S: ServerFnRegistration + 'static>(self, _marker: S) -> Self {
		if let Some(existing) = self
			.registered_endpoints()
			.into_iter()
			.find(|endpoint| endpoint.method == Method::POST && endpoint.path == S::PATH)
		{
			return self.with_configuration_error(duplicate_server_fn_path_error(
				S::PATH,
				[
					S::MODULE_PATH,
					existing
						.origin
						.map_or("<manual-server-fn>", |origin| origin.module_path),
				],
			));
		}

		self.endpoint_with_origin(
			|| ServerFnEndpoint::<S>(PhantomData),
			RouteOrigin::generated(S::MODULE_PATH),
		)
	}

	fn auto_server_fns(self, caller_module: &'static str) -> Self {
		collect_auto_server_fns(self, caller_module)
	}

	fn auto_server_fns_in_crate(
		self,
		caller_module: &'static str,
		caller_crate: &'static str,
	) -> Self {
		crate::server_fn::auto_registration::collect_auto_server_fns_in_crate(
			self,
			caller_module,
			caller_crate,
		)
	}

	fn server_fnset<S: ServerFnSetRegistration>(self, set: S) -> Self {
		set.register(self)
	}
}

struct ServerFnEndpoint<S>(PhantomData<S>);

#[inline]
fn response_content_type(codec: &str) -> HeaderValue {
	match codec {
		"msgpack" => HeaderValue::from_static("application/msgpack"),
		_ => HeaderValue::from_static("application/json"),
	}
}

#[inline]
fn response_with_codec_body<S: ServerFnRegistration>(
	status: StatusCode,
	body: bytes::Bytes,
) -> Response {
	if S::IS_JSON_CODEC {
		Response::from_json_body(status, body)
	} else {
		Response::from_typed_header_body(
			status,
			CONTENT_TYPE,
			response_content_type(S::CODEC),
			body,
		)
	}
}

impl<S: ServerFnRegistration> EndpointInfo for ServerFnEndpoint<S> {
	fn path() -> &'static str {
		S::PATH
	}

	fn method() -> Method {
		Method::POST
	}

	fn name() -> &'static str {
		S::NAME
	}
}

#[async_trait::async_trait]
impl<S: ServerFnRegistration> Handler for ServerFnEndpoint<S> {
	async fn handle(&self, req: Request) -> Result<Response> {
		// Insert a shared cookie jar only for handlers that can access request
		// extensions. Plain body-only server functions cannot set response cookies.
		let cookie_jar = if S::USES_RESPONSE_COOKIE_JAR {
			let jar = SharedResponseCookies::new();
			req.extensions.insert(jar.clone());
			Some(jar)
		} else {
			None
		};

		let mut response = match S::handle(req).await {
			Ok(body) => response_with_codec_body::<S>(StatusCode::OK, body),
			Err(error_body) => {
				let name = S::NAME;
				let path = S::PATH;
				// Log the error to stderr for debugging.
				eprintln!(
					"[server_fn ERROR] {} ({}): {}",
					name,
					path,
					String::from_utf8_lossy(&error_body)
				);

				let status_code = StatusCode::from_u16(S::error_status(&error_body))
					.unwrap_or(StatusCode::INTERNAL_SERVER_ERROR);

				Response::from_json_body(status_code, error_body)
			}
		};

		// Apply response cookies from the shared cookie jar.
		if let Some(cookie_jar) = cookie_jar {
			let cookies = cookie_jar.take();
			for cookie in cookies.cookies() {
				response = response.append_header("Set-Cookie", cookie);
			}
		}

		Ok(response)
	}
}
