use indexmap::IndexMap;
use serde::de::DeserializeOwned;
use serde_json::Value;

use super::builder::BuildError;
use super::fragment::{HasSettings, SettingsFragment};
use super::profile::Profile;
use super::schema::{SettingsResolutionMetadata, SettingsRootSchema};
use super::validation::ValidationResult;

/// Trait for composed settings structs generated by the `#[settings(...)]` macro.
///
/// Provides required field validation against merged configuration sources
/// and fragment-level validation delegation.
pub trait ComposedSettings: Sized + DeserializeOwned {
	/// Check that all required fields have values in the merged source.
	///
	/// The merged data is a flat `IndexMap<String, Value>` from `MergedSettings`.
	/// Field names are looked up as top-level keys (due to `#[serde(flatten)]`).
	/// Generated composed settings preserve legacy root-direct
	/// `BuildError::MissingRequiredField` diagnostics and validate nested nodes
	/// with full `SettingsPathBuf` paths.
	fn validate_requirements(merged: &IndexMap<String, Value>) -> Result<(), BuildError>;

	/// Capture value-free metadata for the resolved configuration.
	fn resolution_metadata(
		merged: &IndexMap<String, Value>,
	) -> Result<SettingsResolutionMetadata, BuildError> {
		let _ = merged;
		Err(BuildError::ResolutionMetadataUnavailable {
			settings_type: std::any::type_name::<Self>(),
		})
	}

	/// Build the runtime verification schema for this composed settings root.
	///
	/// Implementations generated by `#[settings(...)]` expose every accepted
	/// root key and its recursively traversable fragment schema. The empty
	/// default preserves compatibility for hand-written implementations.
	fn root_schema() -> SettingsRootSchema {
		SettingsRootSchema {
			sections: Vec::new(),
		}
	}

	/// Run all fragment `validate()` methods.
	fn validate_fragments(&self, profile: &Profile) -> ValidationResult;
}

/// Fully resolved settings paired with value-free resolution metadata.
pub struct ResolvedSettings<T> {
	pub(crate) settings: T,
	pub(crate) metadata: SettingsResolutionMetadata,
}

impl<T> ResolvedSettings<T> {
	/// Borrow the resolved settings value.
	pub fn settings(&self) -> &T {
		&self.settings
	}

	/// Borrow the value-free resolution metadata.
	pub fn metadata(&self) -> &SettingsResolutionMetadata {
		&self.metadata
	}

	/// Split the resolved settings value and its metadata.
	pub fn into_parts(self) -> (T, SettingsResolutionMetadata) {
		(self.settings, self.metadata)
	}
}

impl<T, F> HasSettings<F> for ResolvedSettings<T>
where
	F: SettingsFragment,
	T: HasSettings<F>,
{
	fn get_settings(&self) -> &F {
		self.settings.get_settings()
	}
}
