use indexmap::IndexMap;
use serde::de::DeserializeOwned;
use serde_json::Value;
use std::marker::PhantomData;

use super::builder::{BuildError, MergedSettings, deserialize_composed};
use super::fragment::{HasSettings, SettingsFragment};
use super::profile::Profile;
use super::schema::{SettingsResolutionMetadata, SettingsRootSchema};
use super::validation::ValidationResult;

/// Trait for composed settings structs generated by the `#[settings(...)]` macro.
///
/// Provides required field validation against merged configuration sources
/// and fragment-level validation delegation.
pub trait ComposedSettings: Sized + DeserializeOwned {
	/// Check that all required fields have values in the merged source.
	///
	/// The merged data is a flat `IndexMap<String, Value>` from `MergedSettings`.
	/// Field names are looked up as top-level keys (due to `#[serde(flatten)]`).
	/// Generated composed settings preserve legacy root-direct
	/// `BuildError::MissingRequiredField` diagnostics and validate nested nodes
	/// with full `SettingsPathBuf` paths.
	fn validate_requirements(merged: &IndexMap<String, Value>) -> Result<(), BuildError>;

	/// Capture value-free metadata for the resolved configuration.
	fn resolution_metadata(
		merged: &IndexMap<String, Value>,
	) -> Result<SettingsResolutionMetadata, BuildError> {
		let _ = merged;
		Err(BuildError::ResolutionMetadataUnavailable {
			settings_type: std::any::type_name::<Self>(),
		})
	}

	/// Build the runtime verification schema for this composed settings root.
	///
	/// Implementations generated by `#[settings(...)]` expose every accepted
	/// root key and its recursively traversable fragment schema. The empty
	/// default preserves compatibility for hand-written implementations.
	fn root_schema() -> SettingsRootSchema {
		SettingsRootSchema {
			sections: Vec::new(),
		}
	}

	/// Run all fragment `validate()` methods.
	fn validate_fragments(&self, profile: &Profile) -> ValidationResult;
}

/// Fully resolved settings paired with value-free resolution metadata.
pub struct ResolvedSettings<T> {
	pub(crate) settings: T,
	pub(crate) metadata: SettingsResolutionMetadata,
}

/// Merged settings awaiting required-field validation and typed deserialization.
pub struct PendingSettings<T> {
	pub(crate) merged: MergedSettings,
	pub(crate) root_schema: SettingsRootSchema,
	pub(crate) typed_coercion: bool,
	pub(crate) marker: PhantomData<fn() -> T>,
}

/// Validation-ready settings inputs retained without serializing secret values.
pub struct SettingsContractState {
	/// Generated schema for the composed settings root.
	pub root_schema: SettingsRootSchema,
	/// Merged configuration values.
	pub merged: IndexMap<String, Value>,
	/// Whether typed string coercion is enabled.
	pub typed_coercion: bool,
}

impl<T: ComposedSettings> PendingSettings<T> {
	/// Clone the merged settings inputs required by contract validation.
	pub fn contract_state(&self) -> SettingsContractState {
		SettingsContractState {
			root_schema: self.root_schema.clone(),
			merged: self.merged.as_map().clone(),
			typed_coercion: self.typed_coercion,
		}
	}

	/// Validate required values and deserialize the composed settings.
	pub fn resolve(&self) -> Result<ResolvedSettings<T>, BuildError> {
		T::validate_requirements(self.merged.as_map())?;
		let metadata = T::resolution_metadata(self.merged.as_map())?;
		let settings = deserialize_composed(self.merged.clone(), self.typed_coercion)?;
		Ok(ResolvedSettings { settings, metadata })
	}

	/// Deserialize one merged top-level settings section.
	pub fn deserialize_section<U: DeserializeOwned>(&self, key: &str) -> Result<U, BuildError> {
		self.merged.get(key).map_err(BuildError::from)
	}
}

impl<T> ResolvedSettings<T> {
	/// Borrow the resolved settings value.
	pub fn settings(&self) -> &T {
		&self.settings
	}

	/// Borrow the value-free resolution metadata.
	pub fn metadata(&self) -> &SettingsResolutionMetadata {
		&self.metadata
	}

	/// Split the resolved settings value and its metadata.
	pub fn into_parts(self) -> (T, SettingsResolutionMetadata) {
		(self.settings, self.metadata)
	}
}

impl<T, F> HasSettings<F> for ResolvedSettings<T>
where
	F: SettingsFragment,
	T: HasSettings<F>,
{
	fn get_settings(&self) -> &F {
		self.settings.get_settings()
	}
}
