name: Coverage

on:
  push:
    branches:
      - main
      - 'develop/*'
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

concurrency:
  group: coverage-${{ github.ref }}
  cancel-in-progress: true

jobs:
  coverage:
    name: Coverage
    uses: ./.github/workflows/coverage.yml
    secrets: inherit
    with:
      runner: '"ubuntu-latest"'
      cargo-build-jobs: '1'
